---
- name: Get tar.gz
  get_url:
    url: https://get.helm.sh/helm-v3.4.2-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz
    checksum: sha256:cacde7768420dd41111a4630e047c231afa01f67e49cc0c6429563e024da4b98
  
- name: Create temporary directory to unarchive helm.tar.gz
  file:
    path: /tmp/1/
    state: directory


- unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/1/
    remote_src: yes

- name: install binary in /usr/local/bin/helm
  copy:
    src: /tmp/1/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: '0555'
    remote_src: yes