---
apiVersion: v1
kind: Service
metadata:
  name: local-git-server
  labels:
    app: local-git-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: local-git-server
