---
apiVersion: v1
kind: Service
metadata:
  name: daemon
  labels:
    app: daemon
spec:
  type: ClusterIP
  ports:
    - name: git
      port: 9418
      targetPort: git
      protocol: TCP
  selector:
    app: daemon
