---
apiVersion: v1
kind: Service
metadata:
  name: local-git-server
  labels:
    app: local-git-server
spec:
  type: ClusterIP
  ports:
    - name: git
      port: 9418
      targetPort: git
      protocol: TCP
  selector:
    app: local-git-server
