apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git://daemon.localgit.svc.cluster.local/
    targetRevision: HEAD
    path: argocd-apps/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: helm
