apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git://daemon.localgit.svc.cluster.local/
    targetRevision: HEAD
    path: argocd-apps/argocd-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-apps
  syncPolicy:
    automated: {}