---
apiVersion: v1
kind: Service
metadata:
  name: cache
  labels:
    app: dockerio
spec:
  type: ClusterIP
  ports:
    - name: registry
      port: 5000
      targetPort: git
      protocol: TCP
  selector:
    app: dockerio
