---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daemon
spec:
  selector:
    matchLabels:
      app: daemon
  template:
    metadata:
      labels:
        app: daemon
    spec:
      containers:
        - image: bitnami/git
          name: main
          command:
            - git 
            - daemon 
            - --base-path=/app
            - --reuseaddr 
            - --export-all
          ports:
            - name: git
              containerPort: 9418
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: hostvol
      volumes:
        - name: hostvol
          hostPath:
            path: /mnt/hostpath
