---
- name: Add namespace
  community.kubernetes.k8s:
    name: '{{ namespace }}'
    api_version: v1
    kind: Namespace
    state: present

- name: Install application
  community.kubernetes.k8s:
    namespace: '{{ namespace }}'
    src: selfreference.yml
